//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.WebServiceVucem.ListarPedimentoService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.ventanillaunica.gob.mx/ventanilla/pedimentos/ws/service/server/listarp" +
        "edimentos/", ConfigurationName="ListarPedimentoService.ListarPedimentosServicePortType")]
    public interface ListarPedimentosServicePortType {
        
        // CODEGEN: Generating message contract since the operation consultarPedimentos is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ventanillaunica.gob.mx/ventanilla/ListarPedimentosService/consultarPed" +
            "imentos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RespuestaBase))]
        App.WebServiceVucem.ListarPedimentoService.consultarPedimentosResponse consultarPedimentos(App.WebServiceVucem.ListarPedimentoService.consultarPedimentosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ventanillaunica.gob.mx/ventanilla/ListarPedimentosService/consultarPed" +
            "imentos", ReplyAction="*")]
        System.Threading.Tasks.Task<App.WebServiceVucem.ListarPedimentoService.consultarPedimentosResponse> consultarPedimentosAsync(App.WebServiceVucem.ListarPedimentoService.consultarPedimentosRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ventanillaunica.gob.mx/pedimentos/ws/oxml/listarpedimentos")]
    public partial class ConsultarPedimentosPeticion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Peticion peticionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Peticion peticion {
            get {
                return this.peticionField;
            }
            set {
                this.peticionField = value;
                this.RaisePropertyChanged("peticion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ventanillaunica.gob.mx/pedimentos/ws/oxml/listarpedimentos")]
    public partial class Peticion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int aduanaField;
        
        private int patenteField;
        
        private long pedimentoField;
        
        private string eDocumentCoveField;
        
        private string rfcField;
        
        private string contenedorField;
        
        private string guiaField;
        
        private System.DateTime fechaInicioField;
        
        private System.DateTime fechaFinField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int aduana {
            get {
                return this.aduanaField;
            }
            set {
                this.aduanaField = value;
                this.RaisePropertyChanged("aduana");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int patente {
            get {
                return this.patenteField;
            }
            set {
                this.patenteField = value;
                this.RaisePropertyChanged("patente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public long pedimento {
            get {
                return this.pedimentoField;
            }
            set {
                this.pedimentoField = value;
                this.RaisePropertyChanged("pedimento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string eDocumentCove {
            get {
                return this.eDocumentCoveField;
            }
            set {
                this.eDocumentCoveField = value;
                this.RaisePropertyChanged("eDocumentCove");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string rfc {
            get {
                return this.rfcField;
            }
            set {
                this.rfcField = value;
                this.RaisePropertyChanged("rfc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string contenedor {
            get {
                return this.contenedorField;
            }
            set {
                this.contenedorField = value;
                this.RaisePropertyChanged("contenedor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string guia {
            get {
                return this.guiaField;
            }
            set {
                this.guiaField = value;
                this.RaisePropertyChanged("guia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=7)]
        public System.DateTime fechaInicio {
            get {
                return this.fechaInicioField;
            }
            set {
                this.fechaInicioField = value;
                this.RaisePropertyChanged("fechaInicio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=8)]
        public System.DateTime fechaFin {
            get {
                return this.fechaFinField;
            }
            set {
                this.fechaFinField = value;
                this.RaisePropertyChanged("fechaFin");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ventanillaunica.gob.mx/pedimentos/ws/oxml/comunes")]
    public partial class Aduana : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string claveField;
        
        private string descripcionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string clave {
            get {
                return this.claveField;
            }
            set {
                this.claveField = value;
                this.RaisePropertyChanged("clave");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ventanillaunica.gob.mx/pedimentos/ws/oxml/listarpedimentos")]
    public partial class Pedimento : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Aduana aduanaField;
        
        private int petenteField;
        
        private long numeroDocumentoAgenteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Aduana aduana {
            get {
                return this.aduanaField;
            }
            set {
                this.aduanaField = value;
                this.RaisePropertyChanged("aduana");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int petente {
            get {
                return this.petenteField;
            }
            set {
                this.petenteField = value;
                this.RaisePropertyChanged("petente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public long numeroDocumentoAgente {
            get {
                return this.numeroDocumentoAgenteField;
            }
            set {
                this.numeroDocumentoAgenteField = value;
                this.RaisePropertyChanged("numeroDocumentoAgente");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ConsultarPedimentosRespuesta))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ventanillaunica.gob.mx/common/ws/oxml/respuesta")]
    public partial class RespuestaBase : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool tieneErrorField;
        
        private string[] errorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool tieneError {
            get {
                return this.tieneErrorField;
            }
            set {
                this.tieneErrorField = value;
                this.RaisePropertyChanged("tieneError");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("mensaje", typeof(string), IsNullable=false)]
        public string[] error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
                this.RaisePropertyChanged("error");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ventanillaunica.gob.mx/pedimentos/ws/oxml/listarpedimentos")]
    public partial class ConsultarPedimentosRespuesta : RespuestaBase {
        
        private Pedimento[] pedimentoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("pedimento", Order=0)]
        public Pedimento[] pedimento {
            get {
                return this.pedimentoField;
            }
            set {
                this.pedimentoField = value;
                this.RaisePropertyChanged("pedimento");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultarPedimentosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ventanillaunica.gob.mx/pedimentos/ws/oxml/listarpedimentos", Order=0)]
        public App.WebServiceVucem.ListarPedimentoService.ConsultarPedimentosPeticion consultarPedimentosPeticion;
        
        public consultarPedimentosRequest() {
        }
        
        public consultarPedimentosRequest(App.WebServiceVucem.ListarPedimentoService.ConsultarPedimentosPeticion consultarPedimentosPeticion) {
            this.consultarPedimentosPeticion = consultarPedimentosPeticion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultarPedimentosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ventanillaunica.gob.mx/pedimentos/ws/oxml/listarpedimentos", Order=0)]
        public App.WebServiceVucem.ListarPedimentoService.ConsultarPedimentosRespuesta consultarPedimentosRespuesta;
        
        public consultarPedimentosResponse() {
        }
        
        public consultarPedimentosResponse(App.WebServiceVucem.ListarPedimentoService.ConsultarPedimentosRespuesta consultarPedimentosRespuesta) {
            this.consultarPedimentosRespuesta = consultarPedimentosRespuesta;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ListarPedimentosServicePortTypeChannel : App.WebServiceVucem.ListarPedimentoService.ListarPedimentosServicePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ListarPedimentosServicePortTypeClient : System.ServiceModel.ClientBase<App.WebServiceVucem.ListarPedimentoService.ListarPedimentosServicePortType>, App.WebServiceVucem.ListarPedimentoService.ListarPedimentosServicePortType {
        
        public ListarPedimentosServicePortTypeClient() {
        }
        
        public ListarPedimentosServicePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ListarPedimentosServicePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ListarPedimentosServicePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ListarPedimentosServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        App.WebServiceVucem.ListarPedimentoService.consultarPedimentosResponse App.WebServiceVucem.ListarPedimentoService.ListarPedimentosServicePortType.consultarPedimentos(App.WebServiceVucem.ListarPedimentoService.consultarPedimentosRequest request) {
            return base.Channel.consultarPedimentos(request);
        }
        
        public App.WebServiceVucem.ListarPedimentoService.ConsultarPedimentosRespuesta consultarPedimentos(App.WebServiceVucem.ListarPedimentoService.ConsultarPedimentosPeticion consultarPedimentosPeticion) {
            App.WebServiceVucem.ListarPedimentoService.consultarPedimentosRequest inValue = new App.WebServiceVucem.ListarPedimentoService.consultarPedimentosRequest();
            inValue.consultarPedimentosPeticion = consultarPedimentosPeticion;
            App.WebServiceVucem.ListarPedimentoService.consultarPedimentosResponse retVal = ((App.WebServiceVucem.ListarPedimentoService.ListarPedimentosServicePortType)(this)).consultarPedimentos(inValue);
            return retVal.consultarPedimentosRespuesta;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<App.WebServiceVucem.ListarPedimentoService.consultarPedimentosResponse> App.WebServiceVucem.ListarPedimentoService.ListarPedimentosServicePortType.consultarPedimentosAsync(App.WebServiceVucem.ListarPedimentoService.consultarPedimentosRequest request) {
            return base.Channel.consultarPedimentosAsync(request);
        }
        
        public System.Threading.Tasks.Task<App.WebServiceVucem.ListarPedimentoService.consultarPedimentosResponse> consultarPedimentosAsync(App.WebServiceVucem.ListarPedimentoService.ConsultarPedimentosPeticion consultarPedimentosPeticion) {
            App.WebServiceVucem.ListarPedimentoService.consultarPedimentosRequest inValue = new App.WebServiceVucem.ListarPedimentoService.consultarPedimentosRequest();
            inValue.consultarPedimentosPeticion = consultarPedimentosPeticion;
            return ((App.WebServiceVucem.ListarPedimentoService.ListarPedimentosServicePortType)(this)).consultarPedimentosAsync(inValue);
        }
    }
}
