// <auto-generated />
namespace App.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class patenteyaduanaenlistapedimento : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(patenteyaduanaenlistapedimento));
        
        string IMigrationMetadata.Id
        {
            get { return "201611011540226_patente y aduana en listapedimento"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
