// <auto-generated />
namespace App.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class relacionListaPedimentoPedimento : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(relacionListaPedimentoPedimento));
        
        string IMigrationMetadata.Id
        {
            get { return "201610071937448_relacion ListaPedimento-Pedimento"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
