//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.WebServiceVucem.PartidaService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.ventanillaunica.gob.mx/ventanilla/pedimentos/ws/service/server/consult" +
        "arpartida/", ConfigurationName="PartidaService.ConsultarPartidaServicePortType")]
    public interface ConsultarPartidaServicePortType {
        
        // CODEGEN: Generating message contract since the operation consultarPartida is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ventanillaunica.gob.mx/ventanilla/ConsultarPartidaService/consultarPar" +
            "tida", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RespuestaBase))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PeticionPedimento))]
        App.WebServiceVucem.PartidaService.consultarPartidaResponse consultarPartida(App.WebServiceVucem.PartidaService.consultarPartidaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ventanillaunica.gob.mx/ventanilla/ConsultarPartidaService/consultarPar" +
            "tida", ReplyAction="*")]
        System.Threading.Tasks.Task<App.WebServiceVucem.PartidaService.consultarPartidaResponse> consultarPartidaAsync(App.WebServiceVucem.PartidaService.consultarPartidaRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ventanillaunica.gob.mx/pedimentos/ws/oxml/consultarpartida")]
    public partial class ConsultarPartidaPeticion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private PeticionPartida peticionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public PeticionPartida peticion {
            get {
                return this.peticionField;
            }
            set {
                this.peticionField = value;
                this.RaisePropertyChanged("peticion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ventanillaunica.gob.mx/pedimentos/ws/oxml/consultarpartida")]
    public partial class PeticionPartida : PeticionPedimento {
        
        private long numeroOperacionField;
        
        private int numeroPartidaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long numeroOperacion {
            get {
                return this.numeroOperacionField;
            }
            set {
                this.numeroOperacionField = value;
                this.RaisePropertyChanged("numeroOperacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int numeroPartida {
            get {
                return this.numeroPartidaField;
            }
            set {
                this.numeroPartidaField = value;
                this.RaisePropertyChanged("numeroPartida");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PeticionPartida))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ventanillaunica.gob.mx/pedimentos/ws/oxml/comunes")]
    public partial class PeticionPedimento : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string aduanaField;
        
        private int patenteField;
        
        private long pedimentoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string aduana {
            get {
                return this.aduanaField;
            }
            set {
                this.aduanaField = value;
                this.RaisePropertyChanged("aduana");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int patente {
            get {
                return this.patenteField;
            }
            set {
                this.patenteField = value;
                this.RaisePropertyChanged("patente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public long pedimento {
            get {
                return this.pedimentoField;
            }
            set {
                this.pedimentoField = value;
                this.RaisePropertyChanged("pedimento");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ventanillaunica.gob.mx/pedimentos/ws/oxml/comunes")]
    public partial class ContribucionAmparoArt303TLC : object, System.ComponentModel.INotifyPropertyChanged {
        
        private decimal valorMercanciaNoOriginariaField;
        
        private decimal montoIGIField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public decimal valorMercanciaNoOriginaria {
            get {
                return this.valorMercanciaNoOriginariaField;
            }
            set {
                this.valorMercanciaNoOriginariaField = value;
                this.RaisePropertyChanged("valorMercanciaNoOriginaria");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public decimal montoIGI {
            get {
                return this.montoIGIField;
            }
            set {
                this.montoIGIField = value;
                this.RaisePropertyChanged("montoIGI");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ventanillaunica.gob.mx/pedimentos/ws/oxml/comunes")]
    public partial class FormaPago : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int claveField;
        
        private string descripcionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int clave {
            get {
                return this.claveField;
            }
            set {
                this.claveField = value;
                this.RaisePropertyChanged("clave");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ventanillaunica.gob.mx/pedimentos/ws/oxml/comunes")]
    public partial class Importe : object, System.ComponentModel.INotifyPropertyChanged {
        
        private FormaPago formaPagoField;
        
        private decimal importeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public FormaPago formaPago {
            get {
                return this.formaPagoField;
            }
            set {
                this.formaPagoField = value;
                this.RaisePropertyChanged("formaPago");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public decimal importe {
            get {
                return this.importeField;
            }
            set {
                this.importeField = value;
                this.RaisePropertyChanged("importe");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ventanillaunica.gob.mx/pedimentos/ws/oxml/comunes")]
    public partial class TipoTasa : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int claveField;
        
        private string descripcionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int clave {
            get {
                return this.claveField;
            }
            set {
                this.claveField = value;
                this.RaisePropertyChanged("clave");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ventanillaunica.gob.mx/pedimentos/ws/oxml/comunes")]
    public partial class Tasa : object, System.ComponentModel.INotifyPropertyChanged {
        
        private TipoTasa claveField;
        
        private decimal tasaAplicableField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public TipoTasa clave {
            get {
                return this.claveField;
            }
            set {
                this.claveField = value;
                this.RaisePropertyChanged("clave");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public decimal tasaAplicable {
            get {
                return this.tasaAplicableField;
            }
            set {
                this.tasaAplicableField = value;
                this.RaisePropertyChanged("tasaAplicable");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ventanillaunica.gob.mx/pedimentos/ws/oxml/comunes")]
    public partial class ClaveGravamen : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int claveField;
        
        private string descripcionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int clave {
            get {
                return this.claveField;
            }
            set {
                this.claveField = value;
                this.RaisePropertyChanged("clave");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ventanillaunica.gob.mx/pedimentos/ws/oxml/comunes")]
    public partial class Gravamen : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ClaveGravamen claveGravamenField;
        
        private Tasa[] tasasField;
        
        private Importe[] importesField;
        
        private ContribucionAmparoArt303TLC[] contribucionAmparoArt303TLCField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ClaveGravamen claveGravamen {
            get {
                return this.claveGravamenField;
            }
            set {
                this.claveGravamenField = value;
                this.RaisePropertyChanged("claveGravamen");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("tasas", Order=1)]
        public Tasa[] tasas {
            get {
                return this.tasasField;
            }
            set {
                this.tasasField = value;
                this.RaisePropertyChanged("tasas");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("importes", Order=2)]
        public Importe[] importes {
            get {
                return this.importesField;
            }
            set {
                this.importesField = value;
                this.RaisePropertyChanged("importes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("contribucionAmparoArt303TLC", Order=3)]
        public ContribucionAmparoArt303TLC[] contribucionAmparoArt303TLC {
            get {
                return this.contribucionAmparoArt303TLCField;
            }
            set {
                this.contribucionAmparoArt303TLCField = value;
                this.RaisePropertyChanged("contribucionAmparoArt303TLC");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ventanillaunica.gob.mx/pedimentos/ws/oxml/comunes")]
    public partial class InstitucionEmisora : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int claveField;
        
        private string descripcionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int clave {
            get {
                return this.claveField;
            }
            set {
                this.claveField = value;
                this.RaisePropertyChanged("clave");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ventanillaunica.gob.mx/pedimentos/ws/oxml/comunes")]
    public partial class CuentaAduanera : object, System.ComponentModel.INotifyPropertyChanged {
        
        private InstitucionEmisora institucionEmisoraField;
        
        private string numeroCuentaField;
        
        private string folioConstanciaField;
        
        private System.DateTime fechaConstanciaField;
        
        private string tipoCuentaField;
        
        private string tipoGarantiaField;
        
        private decimal totalGarantiaField;
        
        private decimal cantidadUMCField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public InstitucionEmisora institucionEmisora {
            get {
                return this.institucionEmisoraField;
            }
            set {
                this.institucionEmisoraField = value;
                this.RaisePropertyChanged("institucionEmisora");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string numeroCuenta {
            get {
                return this.numeroCuentaField;
            }
            set {
                this.numeroCuentaField = value;
                this.RaisePropertyChanged("numeroCuenta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string folioConstancia {
            get {
                return this.folioConstanciaField;
            }
            set {
                this.folioConstanciaField = value;
                this.RaisePropertyChanged("folioConstancia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=3)]
        public System.DateTime fechaConstancia {
            get {
                return this.fechaConstanciaField;
            }
            set {
                this.fechaConstanciaField = value;
                this.RaisePropertyChanged("fechaConstancia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string tipoCuenta {
            get {
                return this.tipoCuentaField;
            }
            set {
                this.tipoCuentaField = value;
                this.RaisePropertyChanged("tipoCuenta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string tipoGarantia {
            get {
                return this.tipoGarantiaField;
            }
            set {
                this.tipoGarantiaField = value;
                this.RaisePropertyChanged("tipoGarantia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public decimal totalGarantia {
            get {
                return this.totalGarantiaField;
            }
            set {
                this.totalGarantiaField = value;
                this.RaisePropertyChanged("totalGarantia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public decimal cantidadUMC {
            get {
                return this.cantidadUMCField;
            }
            set {
                this.cantidadUMCField = value;
                this.RaisePropertyChanged("cantidadUMC");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ventanillaunica.gob.mx/pedimentos/ws/oxml/comunes")]
    public partial class ClaveIdentificador : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string claveField;
        
        private string descripcionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string clave {
            get {
                return this.claveField;
            }
            set {
                this.claveField = value;
                this.RaisePropertyChanged("clave");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ventanillaunica.gob.mx/pedimentos/ws/oxml/comunes")]
    public partial class Identificador : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ClaveIdentificador claveIdentificadorField;
        
        private string complemento1Field;
        
        private string complemento2Field;
        
        private string complemento3Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ClaveIdentificador claveIdentificador {
            get {
                return this.claveIdentificadorField;
            }
            set {
                this.claveIdentificadorField = value;
                this.RaisePropertyChanged("claveIdentificador");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string complemento1 {
            get {
                return this.complemento1Field;
            }
            set {
                this.complemento1Field = value;
                this.RaisePropertyChanged("complemento1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string complemento2 {
            get {
                return this.complemento2Field;
            }
            set {
                this.complemento2Field = value;
                this.RaisePropertyChanged("complemento2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string complemento3 {
            get {
                return this.complemento3Field;
            }
            set {
                this.complemento3Field = value;
                this.RaisePropertyChanged("complemento3");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ventanillaunica.gob.mx/pedimentos/ws/oxml/comunes")]
    public partial class ClavePermiso : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string claveField;
        
        private string descripcionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string clave {
            get {
                return this.claveField;
            }
            set {
                this.claveField = value;
                this.RaisePropertyChanged("clave");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ventanillaunica.gob.mx/pedimentos/ws/oxml/comunes")]
    public partial class Permiso : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ClavePermiso clavePermisoField;
        
        private string numeroPermisoField;
        
        private string firmaDescargoField;
        
        private decimal valorComercialDolaresField;
        
        private decimal cantidadUMTUMCField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ClavePermiso clavePermiso {
            get {
                return this.clavePermisoField;
            }
            set {
                this.clavePermisoField = value;
                this.RaisePropertyChanged("clavePermiso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string numeroPermiso {
            get {
                return this.numeroPermisoField;
            }
            set {
                this.numeroPermisoField = value;
                this.RaisePropertyChanged("numeroPermiso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string firmaDescargo {
            get {
                return this.firmaDescargoField;
            }
            set {
                this.firmaDescargoField = value;
                this.RaisePropertyChanged("firmaDescargo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public decimal valorComercialDolares {
            get {
                return this.valorComercialDolaresField;
            }
            set {
                this.valorComercialDolaresField = value;
                this.RaisePropertyChanged("valorComercialDolares");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public decimal cantidadUMTUMC {
            get {
                return this.cantidadUMTUMCField;
            }
            set {
                this.cantidadUMTUMCField = value;
                this.RaisePropertyChanged("cantidadUMTUMC");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ventanillaunica.gob.mx/pedimentos/ws/oxml/comunes")]
    public partial class DatosVehiculo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string vinField;
        
        private long kilometrajeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string vin {
            get {
                return this.vinField;
            }
            set {
                this.vinField = value;
                this.RaisePropertyChanged("vin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long kilometraje {
            get {
                return this.kilometrajeField;
            }
            set {
                this.kilometrajeField = value;
                this.RaisePropertyChanged("kilometraje");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ventanillaunica.gob.mx/pedimentos/ws/oxml/comunes")]
    public partial class Pais : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string claveField;
        
        private string descripcionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string clave {
            get {
                return this.claveField;
            }
            set {
                this.claveField = value;
                this.RaisePropertyChanged("clave");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace= "http://www.ventanillaunica.gob.mx/pedimentos/ws/oxml/comunes")]
    public partial class UnidadMedida : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string claveField;
        
        private string descripcionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string clave {
            get {
                return this.claveField;
            }
            set {
                this.claveField = value;
                this.RaisePropertyChanged("clave");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ventanillaunica.gob.mx/pedimentos/ws/oxml/comunes")]
    public partial class Partida : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int numeroPartidaField;
        
        private string fraccionArancelariaField;
        
        private string subdivisionFraccionField;
        
        private string descripcionMercanciaField;
        
        private UnidadMedida unidadMedidaTarifaField;
        
        private decimal cantidadUnidadMedidaTarifaField;
        
        private UnidadMedida unidadMedidaComercialField;
        
        private decimal cantidadUnidadMedidaComercialField;
        
        private decimal precioUnitarioField;
        
        private decimal valorComercialField;
        
        private decimal valorAduanaField;
        
        private decimal valorDolaresField;
        
        private decimal valorAgregadoField;
        
        private string codigoProductoField;
        
        private string marcaField;
        
        private string modeloField;
        
        private string metodoValoracionField;
        
        private string vinculacionField;
        
        private Pais paisOrigenDestinoField;
        
        private Pais paisVendedorCompradorField;
        
        private DatosVehiculo[] datosVeiculosField;
        
        private Permiso[] permisosField;
        
        private Identificador[] identificadoresField;
        
        private CuentaAduanera[] cuentasAduanerasField;
        
        private Gravamen[] gravamenesField;
        
        private string observacionesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int numeroPartida {
            get {
                return this.numeroPartidaField;
            }
            set {
                this.numeroPartidaField = value;
                this.RaisePropertyChanged("numeroPartida");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string fraccionArancelaria {
            get {
                return this.fraccionArancelariaField;
            }
            set {
                this.fraccionArancelariaField = value;
                this.RaisePropertyChanged("fraccionArancelaria");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string subdivisionFraccion {
            get {
                return this.subdivisionFraccionField;
            }
            set {
                this.subdivisionFraccionField = value;
                this.RaisePropertyChanged("subdivisionFraccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string descripcionMercancia {
            get {
                return this.descripcionMercanciaField;
            }
            set {
                this.descripcionMercanciaField = value;
                this.RaisePropertyChanged("descripcionMercancia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public UnidadMedida unidadMedidaTarifa {
            get {
                return this.unidadMedidaTarifaField;
            }
            set {
                this.unidadMedidaTarifaField = value;
                this.RaisePropertyChanged("unidadMedidaTarifa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public decimal cantidadUnidadMedidaTarifa {
            get {
                return this.cantidadUnidadMedidaTarifaField;
            }
            set {
                this.cantidadUnidadMedidaTarifaField = value;
                this.RaisePropertyChanged("cantidadUnidadMedidaTarifa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public UnidadMedida unidadMedidaComercial {
            get {
                return this.unidadMedidaComercialField;
            }
            set {
                this.unidadMedidaComercialField = value;
                this.RaisePropertyChanged("unidadMedidaComercial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public decimal cantidadUnidadMedidaComercial {
            get {
                return this.cantidadUnidadMedidaComercialField;
            }
            set {
                this.cantidadUnidadMedidaComercialField = value;
                this.RaisePropertyChanged("cantidadUnidadMedidaComercial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public decimal precioUnitario {
            get {
                return this.precioUnitarioField;
            }
            set {
                this.precioUnitarioField = value;
                this.RaisePropertyChanged("precioUnitario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public decimal valorComercial {
            get {
                return this.valorComercialField;
            }
            set {
                this.valorComercialField = value;
                this.RaisePropertyChanged("valorComercial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public decimal valorAduana {
            get {
                return this.valorAduanaField;
            }
            set {
                this.valorAduanaField = value;
                this.RaisePropertyChanged("valorAduana");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public decimal valorDolares {
            get {
                return this.valorDolaresField;
            }
            set {
                this.valorDolaresField = value;
                this.RaisePropertyChanged("valorDolares");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public decimal valorAgregado {
            get {
                return this.valorAgregadoField;
            }
            set {
                this.valorAgregadoField = value;
                this.RaisePropertyChanged("valorAgregado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string codigoProducto {
            get {
                return this.codigoProductoField;
            }
            set {
                this.codigoProductoField = value;
                this.RaisePropertyChanged("codigoProducto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string marca {
            get {
                return this.marcaField;
            }
            set {
                this.marcaField = value;
                this.RaisePropertyChanged("marca");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string modelo {
            get {
                return this.modeloField;
            }
            set {
                this.modeloField = value;
                this.RaisePropertyChanged("modelo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string metodoValoracion {
            get {
                return this.metodoValoracionField;
            }
            set {
                this.metodoValoracionField = value;
                this.RaisePropertyChanged("metodoValoracion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string vinculacion {
            get {
                return this.vinculacionField;
            }
            set {
                this.vinculacionField = value;
                this.RaisePropertyChanged("vinculacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public Pais paisOrigenDestino {
            get {
                return this.paisOrigenDestinoField;
            }
            set {
                this.paisOrigenDestinoField = value;
                this.RaisePropertyChanged("paisOrigenDestino");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public Pais paisVendedorComprador {
            get {
                return this.paisVendedorCompradorField;
            }
            set {
                this.paisVendedorCompradorField = value;
                this.RaisePropertyChanged("paisVendedorComprador");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("datosVeiculos", Order=20)]
        public DatosVehiculo[] datosVeiculos {
            get {
                return this.datosVeiculosField;
            }
            set {
                this.datosVeiculosField = value;
                this.RaisePropertyChanged("datosVeiculos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("permisos", Order=21)]
        public Permiso[] permisos {
            get {
                return this.permisosField;
            }
            set {
                this.permisosField = value;
                this.RaisePropertyChanged("permisos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("identificadores", Order=22)]
        public Identificador[] identificadores {
            get {
                return this.identificadoresField;
            }
            set {
                this.identificadoresField = value;
                this.RaisePropertyChanged("identificadores");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("cuentasAduaneras", Order=23)]
        public CuentaAduanera[] cuentasAduaneras {
            get {
                return this.cuentasAduanerasField;
            }
            set {
                this.cuentasAduanerasField = value;
                this.RaisePropertyChanged("cuentasAduaneras");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("gravamenes", Order=24)]
        public Gravamen[] gravamenes {
            get {
                return this.gravamenesField;
            }
            set {
                this.gravamenesField = value;
                this.RaisePropertyChanged("gravamenes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string observaciones {
            get {
                return this.observacionesField;
            }
            set {
                this.observacionesField = value;
                this.RaisePropertyChanged("observaciones");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ConsultarPartidaRespuesta))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ventanillaunica.gob.mx/common/ws/oxml/respuesta")]
    public partial class RespuestaBase : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool tieneErrorField;
        
        private string[] errorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool tieneError {
            get {
                return this.tieneErrorField;
            }
            set {
                this.tieneErrorField = value;
                this.RaisePropertyChanged("tieneError");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("mensaje", typeof(string), IsNullable=false)]
        public string[] error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
                this.RaisePropertyChanged("error");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ventanillaunica.gob.mx/pedimentos/ws/oxml/consultarpartida")]
    public partial class ConsultarPartidaRespuesta : RespuestaBase {
        
        private Partida partidaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Partida partida {
            get {
                return this.partidaField;
            }
            set {
                this.partidaField = value;
                this.RaisePropertyChanged("partida");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultarPartidaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ventanillaunica.gob.mx/pedimentos/ws/oxml/consultarpartida", Order=0)]
        public App.WebServiceVucem.PartidaService.ConsultarPartidaPeticion consultarPartidaPeticion;
        
        public consultarPartidaRequest() {
        }
        
        public consultarPartidaRequest(App.WebServiceVucem.PartidaService.ConsultarPartidaPeticion consultarPartidaPeticion) {
            this.consultarPartidaPeticion = consultarPartidaPeticion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultarPartidaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ventanillaunica.gob.mx/pedimentos/ws/oxml/consultarpartida", Order=0)]
        public App.WebServiceVucem.PartidaService.ConsultarPartidaRespuesta consultarPartidaRespuesta;
        
        public consultarPartidaResponse() {
        }
        
        public consultarPartidaResponse(App.WebServiceVucem.PartidaService.ConsultarPartidaRespuesta consultarPartidaRespuesta) {
            this.consultarPartidaRespuesta = consultarPartidaRespuesta;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ConsultarPartidaServicePortTypeChannel : App.WebServiceVucem.PartidaService.ConsultarPartidaServicePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConsultarPartidaServicePortTypeClient : System.ServiceModel.ClientBase<App.WebServiceVucem.PartidaService.ConsultarPartidaServicePortType>, App.WebServiceVucem.PartidaService.ConsultarPartidaServicePortType {
        
        public ConsultarPartidaServicePortTypeClient() {
        }
        
        public ConsultarPartidaServicePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConsultarPartidaServicePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsultarPartidaServicePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsultarPartidaServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        App.WebServiceVucem.PartidaService.consultarPartidaResponse App.WebServiceVucem.PartidaService.ConsultarPartidaServicePortType.consultarPartida(App.WebServiceVucem.PartidaService.consultarPartidaRequest request) {
            return base.Channel.consultarPartida(request);
        }
        
        public App.WebServiceVucem.PartidaService.ConsultarPartidaRespuesta consultarPartida(App.WebServiceVucem.PartidaService.ConsultarPartidaPeticion consultarPartidaPeticion) {
            App.WebServiceVucem.PartidaService.consultarPartidaRequest inValue = new App.WebServiceVucem.PartidaService.consultarPartidaRequest();
            inValue.consultarPartidaPeticion = consultarPartidaPeticion;
            App.WebServiceVucem.PartidaService.consultarPartidaResponse retVal = ((App.WebServiceVucem.PartidaService.ConsultarPartidaServicePortType)(this)).consultarPartida(inValue);
            return retVal.consultarPartidaRespuesta;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<App.WebServiceVucem.PartidaService.consultarPartidaResponse> App.WebServiceVucem.PartidaService.ConsultarPartidaServicePortType.consultarPartidaAsync(App.WebServiceVucem.PartidaService.consultarPartidaRequest request) {
            return base.Channel.consultarPartidaAsync(request);
        }
        
        public System.Threading.Tasks.Task<App.WebServiceVucem.PartidaService.consultarPartidaResponse> consultarPartidaAsync(App.WebServiceVucem.PartidaService.ConsultarPartidaPeticion consultarPartidaPeticion) {
            App.WebServiceVucem.PartidaService.consultarPartidaRequest inValue = new App.WebServiceVucem.PartidaService.consultarPartidaRequest();
            inValue.consultarPartidaPeticion = consultarPartidaPeticion;
            return ((App.WebServiceVucem.PartidaService.ConsultarPartidaServicePortType)(this)).consultarPartidaAsync(inValue);
        }
    }
}
